var NOTE_URL = API_HOST + '/note',
    GET_NOTE_URL = NOTE_URL + '/{ID}',
    ADD_NOTE_URL = API_HOST + '/notes',

    REVIEW_URL = API_HOST + '/review',
    GET_REVIEW_URL = REVIEW_URL + '/{ID}',
    ADD_REVIEW_URL = REVIEW_URL + 's',

    COLLECTION_URL = API_HOST + '/collection',
    GET_COLLECTION_URL = COLLECTION_URL + '/{ID}',
    ADD_COLLECTION_URL = COLLECTION_URL,

    MINIBLOG_URL = API_HOST + '/miniblog',
    GET_MINIBLOG_URL = MINIBLOG_URL + '/{ID}',
    ADD_MINIBLOG_URL = MINIBLOG_URL + '/saying',

    RECOMMENDATION_URL = API_HOST + '/recommendation',
    GET_RECOMMENDATION_URL = RECOMMENDATION_URL + '/{ID}',
    ADD_RECOMMENDATION_URL = RECOMMENDATION_URL + 's',

    EVENT_URL = API_HOST + '/event',
    GET_EVENT_URL = EVENT_URL + '/{ID}',
    ADD_EVENT_URL = EVENT_URL + 's',
    GET_EVENT_FOR_CITY_URL = EVENT_URL + '/location/{ID}';
